### PR TITLE
README: Install with `bun`

### PR DESCRIPTION
**Pull request by fholmqvist**

### CODE REVIEW

**Comment by zth** [comment]
Thank you! There's a note just below that code that explains that it's indeed using `npm` and that you can use `bun` if you'd like. If this is the path we want to take forward then that probably needs to be removed, a Bun lockfile added, and the npm lockfile removed.

Reason it's installing with npm and not bun is that I encountered quite a few problems using bun install in the past. But maybe the situation has improved.

**Comment by fholmqvist** [comment]
How I could have missed that is beyond me :joy: 

I've successfully used `bun i` for several projects (running on `Ubuntu 20.2`, `bun 1.0.19-21`) as the package manager / bundler without issues. I do recall some issues with `react` builds with versions prior, is that what you're referring to?

Either way, thank you! I've used several of your bindings over the years. Cheers! :smiley:

**Comment by zth** [comment]
> How I could have missed that is beyond me 😂
> 
> I've successfully used `bun i` for several projects (running on `Ubuntu 20.2`, `bun 1.0.19-21`) as the package manager / bundler without issues. I do recall some issues with `react` builds with versions prior, is that what you're referring to?

Let's merge this! If it doesn't work then people can swap to npm themselves in the project after init.

> Either way, thank you! I've used several of your bindings over the years. Cheers! 😃

Thank you, happy to hear that! 😄 What type of things have you been building with ReScript?

**Comment by fholmqvist** [comment]
I've experimented with using it as a replacement for React, but have previously found the paper cuts to not weigh in favor.

However, the combination of the 11 release (esp. record and annotation improvements) combined with bun means that the avenue of full stack Rescript is starting to look very interesting. I'm currently attempting a full stack demo. If I get around completing it I'll happily share it on the forums :)

**Comment by zth** [comment]
@fholmqvist sounds very interesting, please feel free to reach out if you want to throw ideas around! I haven't properly announced it yet, but I'm working on + using this as a way of building server-focused web apps with ReScript, Bun, JSX and Htmx: https://github.com/zth/res-x. I'm really excited about it, I think that combination has a lot of potential.

**Comment by zth** [comment]
@fholmqvist on topic - I think the CI action needs to be updated to run bun instead of npm install as well.

**Comment by fholmqvist** [comment]
Cheers!

Pipe is passing(?). Took the liberty of also upgrading core to `0.6` and bun wrapper to `0.3.1`.

**Comment by zth** [comment]
@fholmqvist excellent, thank you very much! 

I'd be curious to hear your experience using Bun in ReScript, please keep me posted. Related: there's a editor tooling PR that'll land soon that's going to drastically improve the DX of using some of the more polymorphic Bun APIs: https://github.com/rescript-lang/rescript-vscode/pull/884

**Pull request merged**
